/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package member;

import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Harshvardhan Kale
 */
public class EditMember extends javax.swing.JFrame {

    /**
     * Creates new form EditMember
     */
    private int memberId;
    private int gymId;
    
    public EditMember() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        editMemberLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTF = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        newEmailLabel = new javax.swing.JLabel();
        newEmailTF = new javax.swing.JTextField();
        newPhoneLabel = new javax.swing.JLabel();
        newPhoneTF = new javax.swing.JTextField();
        newBranchNameLabel = new javax.swing.JLabel();
        newBranchNameTF = new javax.swing.JTextField();
        newWeightLabel = new javax.swing.JLabel();
        newBodyFatLabel = new javax.swing.JLabel();
        newInjuryLabel = new javax.swing.JLabel();
        advancePaidLabel = new javax.swing.JLabel();
        newWeightTF = new javax.swing.JTextField();
        newBodyFatTF = new javax.swing.JTextField();
        newInjuryTF = new javax.swing.JTextField();
        advancePaidTF = new javax.swing.JTextField();
        searchTermsLabel = new javax.swing.JLabel();
        updatableDetails = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        findMemberButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(130, 155));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        editMemberLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        editMemberLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit person.png"))); // NOI18N
        editMemberLabel.setText("Edit Member");

        firstNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        firstNameLabel.setText("First Name");

        firstNameTF.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        emailLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLabel.setText("Email-ID");

        emailTF.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        newEmailLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newEmailLabel.setText("Email-ID");

        newEmailTF.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        newPhoneLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newPhoneLabel.setText("Phone Number");

        newPhoneTF.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        newBranchNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newBranchNameLabel.setText("Branch Name");

        newBranchNameTF.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        newWeightLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newWeightLabel.setText("Weight");

        newBodyFatLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newBodyFatLabel.setText("Body Fat (%)");

        newInjuryLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newInjuryLabel.setText("Injury");

        advancePaidLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        advancePaidLabel.setText("Advance Paid");

        newWeightTF.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        newBodyFatTF.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        newInjuryTF.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        advancePaidTF.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        searchTermsLabel.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        searchTermsLabel.setText("Search Terms");

        updatableDetails.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        updatableDetails.setText("Corresponding Updatable Details");

        updateButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        findMemberButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        findMemberButton.setText("Find Member");
        findMemberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findMemberButtonActionPerformed(evt);
            }
        });

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(firstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(75, 75, 75)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(firstNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(emailTF)))
                            .addComponent(searchTermsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(findMemberButton))
                        .addGap(164, 164, 164)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(updatableDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(newPhoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(newEmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(newBranchNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(newEmailTF, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                            .addComponent(newPhoneTF)
                                            .addComponent(newBranchNameTF))
                                        .addGap(164, 164, 164)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(newWeightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(newBodyFatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(newInjuryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(advancePaidLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(updateButton))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(newWeightTF, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                            .addComponent(newBodyFatTF)
                                            .addComponent(newInjuryTF)
                                            .addComponent(advancePaidTF)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(209, 209, 209)
                                        .addComponent(deleteButton)))))
                        .addContainerGap(80, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(editMemberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editMemberLabel)
                    .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTermsLabel)
                    .addComponent(updatableDetails))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newEmailLabel)
                    .addComponent(newEmailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newWeightLabel)
                    .addComponent(newWeightTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPhoneLabel)
                    .addComponent(newPhoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newBodyFatLabel)
                    .addComponent(newBodyFatTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBranchNameLabel)
                    .addComponent(newBranchNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newInjuryLabel)
                    .addComponent(newInjuryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(advancePaidLabel)
                    .addComponent(advancePaidTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(findMemberButton)
                    .addComponent(updateButton))
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        String newEmail = newEmailTF.getText();
        String newPhone = newPhoneTF.getText();
        String newBranchName = newBranchNameTF.getText();
        double newWeight = Double.parseDouble(newWeightTF.getText());
        double newBodyFat = Double.parseDouble(newBodyFatTF.getText());
        String newInjury = newInjuryTF.getText();
        int newAdvancePaid = Integer.parseInt(advancePaidTF.getText());

        MemberDAO memberDAO = new MemberDAO();
        memberDAO.updateMember(memberId, newEmail, newPhone, newBranchName, newWeight, newBodyFat, newInjury, newAdvancePaid);
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        MemberDAO memberDAO = new MemberDAO();
        memberDAO.deleteMember(memberId);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void findMemberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findMemberButtonActionPerformed
        // TODO add your handling code here:
        String firstName = firstNameTF.getText();
        String email = emailTF.getText();
        MemberDAO memberDAO = new MemberDAO();
        List<String> fetchedValues = memberDAO.findMember(firstName, email);

        if(fetchedValues != null) {

            memberId = Integer.parseInt(fetchedValues.get(0));
            gymId = Integer.parseInt(fetchedValues.get(1));

            newEmailTF.setText(fetchedValues.get(2));
            newPhoneTF.setText(fetchedValues.get(3));
            newBranchNameTF.setText(fetchedValues.get(4));
            newWeightTF.setText(fetchedValues.get(5));
            newBodyFatTF.setText(fetchedValues.get(6));
            newInjuryTF.setText(fetchedValues.get(7));
            advancePaidTF.setText(fetchedValues.get(8));
        }

        else 
            JOptionPane.showMessageDialog(null, "Member Not Found");
    }//GEN-LAST:event_findMemberButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel advancePaidLabel;
    private javax.swing.JTextField advancePaidTF;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel editMemberLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTF;
    private javax.swing.JButton findMemberButton;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel newBodyFatLabel;
    private javax.swing.JTextField newBodyFatTF;
    private javax.swing.JLabel newBranchNameLabel;
    private javax.swing.JTextField newBranchNameTF;
    private javax.swing.JLabel newEmailLabel;
    private javax.swing.JTextField newEmailTF;
    private javax.swing.JLabel newInjuryLabel;
    private javax.swing.JTextField newInjuryTF;
    private javax.swing.JLabel newPhoneLabel;
    private javax.swing.JTextField newPhoneTF;
    private javax.swing.JLabel newWeightLabel;
    private javax.swing.JTextField newWeightTF;
    private javax.swing.JLabel searchTermsLabel;
    private javax.swing.JLabel updatableDetails;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
