/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee;

import java.util.Date;

/**
 *
 * @author Harshvardhan Kale
 */
public class AddEmployee extends javax.swing.JFrame {

    /**
     * Creates new form TrainerForm
     */
    public AddEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderBG = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        addEmployeeLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTF = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTF = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        phoneTF = new javax.swing.JTextField();
        dobLabel = new javax.swing.JLabel();
        dobChooser = new com.toedter.calendar.JDateChooser();
        dojLabel = new javax.swing.JLabel();
        dojChooser = new com.toedter.calendar.JDateChooser();
        houseNumberLabel = new javax.swing.JLabel();
        streetLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        streetTF = new javax.swing.JTextField();
        cityTF = new javax.swing.JTextField();
        houseNumberTF = new javax.swing.JTextField();
        zipLabel = new javax.swing.JLabel();
        zipTF = new javax.swing.JTextField();
        personalDetailsLabel = new javax.swing.JLabel();
        addressDetailsLabel = new javax.swing.JLabel();
        saveEmployeeButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        genderLabel = new javax.swing.JLabel();
        maleRB = new javax.swing.JRadioButton();
        femaleRB = new javax.swing.JRadioButton();
        othersRB = new javax.swing.JRadioButton();
        closeButton = new javax.swing.JButton();
        designetionLabel = new javax.swing.JLabel();
        designationCB = new javax.swing.JComboBox<>();
        branchNameLabel = new javax.swing.JLabel();
        branchNameCB = new javax.swing.JComboBox<>();
        passwordLabel = new javax.swing.JLabel();
        passwordPF = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 120));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        addEmployeeLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        addEmployeeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add employee.png"))); // NOI18N
        addEmployeeLabel.setText("Add Employee");

        firstNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        firstNameLabel.setText("First Name");

        firstNameTF.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        lastNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lastNameLabel.setText("Last Name");

        lastNameTF.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        emailLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLabel.setText("Email - ID");

        emailTF.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        phoneLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phoneLabel.setText("Phone Number");

        phoneTF.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        dobLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dobLabel.setText("Date of Birth");

        dobChooser.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        dojLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dojLabel.setText("Date of Joining");

        dojChooser.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        houseNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        houseNumberLabel.setText("House Number");

        streetLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        streetLabel.setText("Street");

        cityLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cityLabel.setText("City");

        streetTF.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        cityTF.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        houseNumberTF.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        zipLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        zipLabel.setText("Zip Code");

        zipTF.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        personalDetailsLabel.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        personalDetailsLabel.setText("Personal and Branch Details");

        addressDetailsLabel.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        addressDetailsLabel.setText("Address Details");

        saveEmployeeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        saveEmployeeButton.setText("Save Employee");
        saveEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveEmployeeButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        genderLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        genderLabel.setText("Gender");

        genderBG.add(maleRB);
        maleRB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        maleRB.setText("Male");

        genderBG.add(femaleRB);
        femaleRB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        femaleRB.setText("Female");

        genderBG.add(othersRB);
        othersRB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        othersRB.setText("Others");

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        designetionLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        designetionLabel.setText("Designation");

        designationCB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        designationCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trainer", "Receptionist", "Dietician", "Admin" }));

        branchNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        branchNameLabel.setText("Branch Name");

        branchNameCB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        branchNameCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pimple Saudagar", "Bhosale Nagar" }));

        passwordLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passwordLabel.setText("Set Password");

        passwordPF.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(dobLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(phoneLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lastNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(firstNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dojLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                                    .addComponent(genderLabel))
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(maleRB)
                                        .addGap(18, 18, 18)
                                        .addComponent(femaleRB)
                                        .addGap(18, 18, 18)
                                        .addComponent(othersRB))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(firstNameTF)
                                                .addComponent(lastNameTF)
                                                .addComponent(phoneTF)
                                                .addComponent(dobChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                                .addComponent(dojChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(164, 164, 164)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(designetionLabel)
                                            .addComponent(branchNameLabel)
                                            .addComponent(passwordLabel))
                                        .addGap(67, 67, 67)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(designationCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(branchNameCB, 0, 220, Short.MAX_VALUE)
                                            .addComponent(passwordPF)))
                                    .addComponent(personalDetailsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(164, 164, 164)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(houseNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(streetLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(zipLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(saveEmployeeButton))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(streetTF)
                                    .addComponent(houseNumberTF)
                                    .addComponent(cityTF)
                                    .addComponent(zipTF, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(clearButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(addressDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(70, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addEmployeeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addEmployeeLabel)
                    .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personalDetailsLabel)
                    .addComponent(addressDetailsLabel))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(houseNumberLabel)
                    .addComponent(houseNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(designetionLabel)
                    .addComponent(designationCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(streetLabel)
                    .addComponent(streetTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(branchNameLabel)
                    .addComponent(branchNameCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLabel)
                    .addComponent(cityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLabel)
                    .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zipLabel)
                    .addComponent(zipTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel)
                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel)
                    .addComponent(maleRB)
                    .addComponent(femaleRB)
                    .addComponent(othersRB))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dobLabel)
                            .addComponent(dobChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dojLabel)
                            .addComponent(dojChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveEmployeeButton)
                            .addComponent(clearButton))
                        .addGap(2, 2, 2)))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        firstNameTF.setText("");
        lastNameTF.setText("");
        phoneTF.setText("");
        emailTF.setText("");
        maleRB.setSelected(false);
        femaleRB.setSelected(false);
        othersRB.setSelected(false);
        dobChooser.setCalendar(null);
        dojChooser.setCalendar(null);
        designationCB.setSelectedIndex(0);
        branchNameCB.setSelectedIndex(0);
        passwordPF.setText("");
        houseNumberTF.setText("");
        streetTF.setText("");
        cityTF.setText("");
        zipTF.setText("");
        
    }//GEN-LAST:event_clearButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void saveEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveEmployeeButtonActionPerformed
        // TODO add your handling code here:
        String firstName = firstNameTF.getText();
        String lastName = lastNameTF.getText();
        String phone = phoneTF.getText();
        String email = emailTF.getText();
        String gender = "";
        
        if(maleRB.isSelected())
            gender = maleRB.getText();
        else if(femaleRB.isSelected())
            gender = femaleRB.getText();
        else if(othersRB.isSelected())
            gender = othersRB.getText();
        
        Date dob = dobChooser.getDate();
        Date doj = dojChooser.getDate();
        String designation = designationCB.getSelectedItem().toString();
        String branchName = branchNameCB.getSelectedItem().toString();
        char[] password = passwordPF.getPassword();
        String houseNumber = houseNumberTF.getText();
        String street = streetTF.getText();
        String city = cityTF.getText();
        String zipcode = zipTF.getText();
        
        Employee employee = new Employee(firstName, lastName, phone, email, gender, dob, doj, designation, branchName, password, houseNumber, street, city, zipcode);
        EmployeeDAO employeeDAO = new EmployeeDAO();
        employeeDAO.addEmployee(employee);
    }//GEN-LAST:event_saveEmployeeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addEmployeeLabel;
    private javax.swing.JLabel addressDetailsLabel;
    private javax.swing.JComboBox<String> branchNameCB;
    private javax.swing.JLabel branchNameLabel;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTF;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JComboBox<String> designationCB;
    private javax.swing.JLabel designetionLabel;
    private com.toedter.calendar.JDateChooser dobChooser;
    private javax.swing.JLabel dobLabel;
    private com.toedter.calendar.JDateChooser dojChooser;
    private javax.swing.JLabel dojLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTF;
    private javax.swing.JRadioButton femaleRB;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTF;
    private javax.swing.ButtonGroup genderBG;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel houseNumberLabel;
    private javax.swing.JTextField houseNumberTF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTF;
    private javax.swing.JRadioButton maleRB;
    private javax.swing.JRadioButton othersRB;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordPF;
    private javax.swing.JLabel personalDetailsLabel;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JButton saveEmployeeButton;
    private javax.swing.JLabel streetLabel;
    private javax.swing.JTextField streetTF;
    private javax.swing.JLabel zipLabel;
    private javax.swing.JTextField zipTF;
    // End of variables declaration//GEN-END:variables
}
